import {
    Button,
    HorizontalBox,
    ProgressIndicator,
    Spinner,
} from "std-widgets.slint";
import { CircularProgressIndicator } from "../circular-progress.slint";
import { Styles } from "../styles.slint";
import { Center } from "center.slint";
import { State } from "../state.slint";

export component Bar inherits Window {
    in-out property <int> counter: 42;
    callback request-increase-value();
    default-font-family: "Satoshi Variable";
    default-font-size: 14px;
    default-font-weight: 500;
    background: Styles.surface_container_lowest;

    VerticalLayout {
        HorizontalLayout {
            spacing: 3px;

            for ws in State.workspaces: Rectangle {
                height: 3px;
                background: ws.id == State.workspaceFocused ? Styles.primary : ws.active_window_id != 0 ? Styles.primary_container : Styles.surface_container;
            }
        }

        HorizontalLayout {
            padding: 2px;
            padding-left: 15px;
            padding-right: 15px;
            spacing: 10px;

            VerticalLayout {
                alignment: center;

                HorizontalLayout {
                    min-width: 250px;
                    alignment: start;
                    horizontal-stretch: 1;
                    spacing: 5px;

                    for stat in [0.15, 0.75, 0.25, 0.55]: CircularProgressIndicator {
                        progress: stat;
                        width: 20px;
                        height: 20px;
                    }
                }
            }

            Center { }

            HorizontalLayout {
                min-width: 250px;
                alignment: end;
                horizontal-stretch: 1;

                Text {
                    vertical-alignment: center;
                    text: "Counter: \{root.counter}";
                }

                Button {
                    text: "Increase value";
                    clicked => {
                        root.request-increase-value();
                    }
                }

                Text {
                    vertical-alignment: center;
                    text: "Active: \{State.workspaceFocused}";
                }
            }
        }
    }
}
